import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: " abcd1",
    firstName: "reddy",
    lastName: "T",
    username: "Reddy",
    password: "reddy1234",
    profilePicture:
      "https://media.licdn.com/dms/image/C4D03AQHv1SvbdPPM9A/profile-displayphoto-shrink_400_400/0/1664248232839?e=1697068800&v=beta&t=vTL-kaB7piXRLJHOXC-4PIIhHPocGu9kLyzfQtQpH9w",
    coverPicture: "",
    description:
      "Senior Software Engineer @Microsoft | Creator of India’s biggest programming community | Tweets about JavaScript, ReactJS, Career and Startups",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd2",
    firstName: "Nirvi",
    lastName: "Nirvi",
    username: "Nirvi",
    password: "nirvi1234",
    profilePicture:
      "https://tse4.mm.bing.net/th?id=OIP.HriNIvVww3aj-tdZrtyZzgHaE8&pid=Api&P=0&h=180",
    coverPicture: "",
    description:
      "Senior Software Engineer @Microsoft | Creator of India’s biggest programming community | Tweets about JavaScript, ReactJS, Career and Startups",
    website: "https://nirviportfolio.com",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd3",
    firstName: "Karthik",
    lastName: "N",
    username: "Karthi",
    password: "Karthi1234",
    profilePicture:
      "https://discoverymood.com/wp-content/uploads/2020/04/Mental-Strong-Women-min-480x340.jpg",
    coverPicture: "",
    description:
      "Senior Software Engineer @Microsoft | Creator of India’s biggest programming community | Tweets about JavaScript, ReactJS, Career and Startups",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd4",
    firstName: "Yuvaraj",
    lastName: "",
    username: "Yuvaraj",
    password: "raju1234",
    profilePicture:
      "https://lh3.googleusercontent.com/fife/AKsag4PxO0ZxAjFuVxwQZMuf7wN3BoWnlB5lpgKRLPcovYQ0Oww7XrfCu8lKOtWvXrWI49i7YRo22Hdx5Km8Ki_TOBmJqnXe688MFsPFbb8h-0Piw3Gti2H33BkMe9P5z2X5WBbLGqYfW0cfsqbQCX5tqnkjpnSGux2DwhCgjQD4E94M7hHMNHpgylde4RlCl6RfsFyYYctB0w7QzR4lsk8MQdT77e_wUF7OYaFaXp7OTLSL6WBgeTzE7Qf30womra3YJHPKAq-BAuh8Zt-26KUpw-vIEgjs5EQV_IlfHjrbrBLHW21XYXL5usM2rewgGMvrTncYy--Nog9woCsgNt_2BsOlGI8tYtfPra8ciAHmK2gMKd-SK-vLZKC24YE59yTG4xoYZ_jCvcHBjgl2AhwxiPhwVzvdcjIRYxM-otMg2xPwBs6qshsFiwRgPWjDhHQAPaXRyQ78omYNz1FKBtnPUAC7QR4cHfBccIBjWhCBmnmlbcLhgKolnoShzp8IZ8apUKKCQDRlpWEb-f_19SgaQ6O1Mvhbj3AaqNIsf_Wr9M_9zLW9Z8GpJeQcXVoAu9gi74odvWtYloNKz3mQoPvnXNAFL422eIdQhMmtVPSNKMVxg_ibkqokIRR7UqtUsm3MaDRxRhwAP-ZBELFuZh0RNx7bqaHpJf7a9wD4JwheAfqMQcbC05JTP8-y8Oog8h9quWFKs5rz2l56exznBkIKRzVLV3SWSQQtzwRHsIwJAO3EtkUuKmCcfqtc5dfHTSqNRCXuZrRLlT0-Zxg-wJ_o5zYomFFqQjLPQe8p3SyMKbNPNiBFkRmFWn3mePqCzvajCF5A0so_VkA6ty2nC8yT0DOwReoi4q3qiLgMxVd9lDCCd0vWio5ZhIDE9tCP5Msl_KhC-RFWzmQk8dLT94FbE8fhROHFgab1vgPHvgMiegKwFNNA2rKpTK5irGtXIaRQjcgXsDnNpaW03NE8yE2aC2K34I7Zp2DetEsB7NTZDF6tBBj2vK3fzW4SE1w5p3IRmjBcZSw0Fn5uwbzcHhexcnZvn_NSO_2I9hYE88SfPP4RCpcXpbR_pz4sCkdWPNAXrT4YTfL65bfGEOSkvMCx9WHWEHYefB5St4GijsMdNx9RzN-jAUwrOoD-h2Y420skbbojgQhUrMYeFrV7EsJLNg8Ts6JUtpZLOvwvMP0s8Dhwjo8t65iaEsGQW93TzINAwWRFfmuH6IgTNjUi0bru6WAnnYB3vCH94mjcRelpbM9m6DjUJN738AjELZjUwddgVZWIfI4WSrhSTygFJlYzTY8-VQknCiOPpVVGhBVpHVuDbCM92dT_h0Ngu_UJYGtHrb_aKNgkqVrQF2rVh2edNnVUmr8R0DMKN7OAvbum9f-MmipBqJjLBbEQ217lKiWOX-hrVrhSSxHHZGPmau7GqBp4Swk2FOFznUjNK4hmgEwqO97K3T7S3mpQHvNtbUOStW1xdqjlfCNoenXjNyiIIxtA-GghCt_OiEwPsSY2EyYfv9S3vx07bG9uQXVA0c6fphRZaBcxJzmTvUsK_gyv=w1920-h828",
    coverPicture: "",
    description: "Actor | Working predominantly in Telugu Cinema.",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd5",
    firstName: "Asswin",
    lastName: "Kumar",
    username: "AsswinK",
    password: "Ashwin1234",
    profilePicture: "",
    coverPicture: "",
    description: "Ladies Man",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd6",
    firstName: "Pruthvi",
    lastName: "Mani",
    username: "Pruthivi",
    password: "Ashwin1234",
    profilePicture: "",
    coverPicture: "",
    description: "Ladies Man",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: " abcd7",
    firstName: "Pruthvi",
    lastName: "Mani",
    username: "Pruthivi",
    password: "Ashwin1234",
    profilePicture: "",
    coverPicture: "",
    description: "Ladies Man",
    website: "",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
